# Spring properties
spring:
  application:
      name: CaasApi
  security:
    username:
    password:

project:
  name: caas-api
  artifactId: caas-api
  description: caas-api management service

# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port

management:     # If you set off security...
  security:
    enabled: false

---
spring:
  profiles: local

kubernetes:
  adminToken: ADMIN_TOKEN
  api:
    endpoint: KUBE_API_ENDPOINT


---
spring:
  profiles: dev

kubernetes:
  adminToken: ADMIN_TOKEN
  api:
    endpoint: KUBE_API_ENDPOINT
