# Spring properties
spring:
  application:
      name: CaasApi
  security:
    username:
    password:

project:
  name: caas-api
  artifactId: caas-api
  description: caas-api management service

caas:
  url:
  testUserToken :

# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port

management:     # If you set off security...
  security:
    enabled: false

---
spring:
  profiles: local

---
spring:
  profiles: dev